### ISSUE TITLE
Delegate When Tapping outside area when dismissing

### ISSUE THREAD

**Issue by harshadanu** [LunabeeStudio/LBBottomSheet#3]
Any option to get a completion block or delegate when manually tapping outside and sheet is getting dismissed. When dismissing by this way, have to do some activity in the View controller.

**Comment by ndominati-luna** [comment]
Hi,

Thanks for your feedback and sorry for the delay.
Indeed we can add this kind of delegate.

We add this to our roadmap and we'll think on how to make this fitting in the component.

**Comment by ndominati-luna** [comment]
Hi,

A new version 1.0.17 has been released and is now containing a `BottomSheetInteractionDelegate` you can give to the bottom sheet controller when presenting it.

I hope it will help you.
